staging:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
local:
  host: localhost # For vagrant, set to the vagrant MySQL IP address 0.0.0.0
  database: db_name
  username: root
  password: 'root'